name: f

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t omarkataa/nginx-action:$GITHUB_RUN_ID .

  login:
    
    needs: build
    runs-on: self-hosted
    steps:
   
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: minddocdev/docker-publish-action@master
      with:
        name: omarkataa/nginx-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Run the build process with Docker
 
      run: docker run -d --name omarkataa -p 80:80 omarkataa/nginx-action:$GITHUB_RUN_ID
    


 
